# PUBLISHER Only Properties
spring.application.name=spring-publisher
server.port=0

spring.cloud.function.definition=activitySupplier

spring.cloud.stream.function.bindings.activitySupplier-out-0=output
#spring.cloud.stream.bindings.output.group=activity
spring.cloud.stream.bindings.output.destination=activities.activity



# Publish Rate 50 ms
spring.integration.poller.fixedDelay=50




## Super Streams
#spring.cloud.stream.bindings.output.producer.partition-count=2
#spring.cloud.stream.bindings.output.producer.partition-key-expression=payload['account']
#spring.cloud.stream.rabbit.bindings.output.producer.producer-type=stream-async
#spring.cloud.stream.rabbit.bindings.output.producer.super-stream=true
#spring.cloud.stream.rabbit.bindings.output.producer.declare-exchange=false
#
#spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
#spring.cloud.stream.rabbit.bindings.output.consumer.containerType=STREAM
#
#
## Super Streams
#spring.cloud.stream.rabbit.bindings.output.consumer.container-type=STREAM
#spring.cloud.stream.rabbit.bindings.output.consumer.super-stream=true
