# PUBLISHER Only Properties
spring.application.name=spring-publisher
server.port=0

spring.cloud.function.definition=alertSupplier

spring.cloud.stream.function.bindings.alertSupplier-out-0=output
spring.cloud.stream.bindings.output.group=alerts.alert
spring.cloud.stream.bindings.output.destination=amq.topic

spring.cloud.stream.rabbit.binder.connection-name-prefix==${spring.application.name}
spring.cloud.stream.rabbit.bindings.output.consumer.containerType=STREAM


# Simplify stream name
spring.cloud.stream.rabbit.bindings.output.consumer.queueNameGroupOnly=true


# Publish Rate 50 ms
spring.integration.poller.fixedDelay=50

